name: Deploy workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and deloy
    runs-on: ubuntu:latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Lint
        run: npm lint
      - name: Tests
        run: npm test
      - name: Build
        run: npm build
