name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and deloy
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo hello
